language: swift
osx_image: macos-15.2

swift:
  - 6.0

script:
  - xcodebuild clean build -scheme SwiftUpdateKit -destination 'platform=macOS'  
  - xcodebuild test -scheme SwiftUpdateKit -destination 'platform=macOS'  