language: swift
osx_image: macos-15.2

swift:
  - 6.0

script:
  - xcodebuild clean build -project SwiftUpdateKit.xcodeproj -scheme SwiftUpdateKit -destination 'platform=macOS'
  - xcodebuild test -project SwiftUpdateKit.xcodeproj -scheme SwiftUpdateKit -destination 'platform=macOS'