language: swift
osx_image: xcode15.2

swift:
  - 6.0

script:
  - xcodebuild clean build -project SwiftUpdateKit.xcodeproj -scheme SwiftUpdateKit -destination 'platform=macOS'
  - xcodebuild archive -scheme SwiftUpdateKit -destination="generic/platform=macOS" -archivePath "./archives/macOS_arm64.xcarchive" ARCHS=arm64 SKIP_INSTALL=NO
  - xcodebuild archive -scheme SwiftUpdateKit -destination="generic/platform=macOS" -archivePath "./archives/macOS_x86_64.xcarchive" ARCHS=x86_64 SKIP_INSTALL=NO
  - xcodebuild -create-xcframework \
      -framework "./archives/macOS_arm64.xcarchive/Products/Library/Frameworks/SwiftUpdateKit.framework" \
      -framework "./archives/macOS_x86_64.xcarchive/Products/Library/Frameworks/SwiftUpdateKit.framework" \
      -output "./SwiftUpdateKit.xcframework"
  - ls -l "./SwiftUpdateKit.xcframework"